version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../project/:/var/www/html
    environment:
      - NGINX_PORT=${NGINX_PORT}
    ports:
      - ${NGINX_PORT}:80
    restart: always
    depends_on:
      - php-fpm
      - db

  php-fpm:
    build: .
    restart: always
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../project/:/var/www/html

  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
